services:
  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - image-resize-network
    command: redis-server --appendonly yes

  # RabbitMQ for job queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672' # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - image-resize-network

volumes:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  image-resize-network:
    driver: bridge
