services:
  # Image Resize API
  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MAX_FILE_SIZE=10485760
      - CACHE_DURATION=24h
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_BUCKET=${SUPABASE_BUCKET}
      - GIN_MODE=release
    depends_on:
      redis:
        condition: service_started
      # rabbitmq:
      #   condition: service_healthy
    volumes:
      - ./uploads:/root/uploads
    restart: unless-stopped
    networks:
      - image-resize-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - image-resize-network
    command: redis-server --appendonly yes

  # RabbitMQ for job queue
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - '5672:5672'
  #     - '15672:15672' # Management UI
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   restart: unless-stopped
  #   networks:
  #     - image-resize-network
  #   healthcheck:
  #     test: ['CMD', 'rabbitmq-diagnostics', 'ping']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  redis_data:
    driver: local
  # rabbitmq_data:
  #   driver: local

networks:
  image-resize-network:
    driver: bridge
